# Generated by Django 4.1.1 on 2023-03-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articlecategorie_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='blog.categorie'),
        ),
        migrations.DeleteModel(
            name='ArticleCategorie',
        ),
    ]
