# Generated by Django 4.1.1 on 2023-03-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_categories_article_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(blank=True, upload_to='imagesblog'),
        ),
    ]
